import {
  Building2,
  Users,
  Plug,
  CreditCard,
  MessageCircle,
  SlidersHorizontal,
  DatabaseBackup,
  Percent,
  Receipt,
  Activity,
  Package,
  Wallet,
  Smartphone,
  Wand2,
  Printer,
} from "lucide-react";
import type { SettingsSectionDefinition } from "./types";
import { EmpresaSection } from "./sections/empresa-section";
import { UsuariosSection } from "./sections/usuarios-section";
import { IntegracoesSection } from "./sections/integracoes-section";
import { BellaPaySection } from "./sections/bella-pay-section";
import { WhatsappSection } from "./sections/whatsapp-section";
import { PreferenciasSection } from "./sections/preferencias-section";
import { BackupSection } from "./sections/backup-section";
import { DiscountPolicySection } from "./sections/discount-policy-section";
import { CupomSection } from "./sections/cupom-section";
import { DiagnosticoSection } from "./sections/diagnostico-section";
import { CustosOperacionaisSection } from "./sections/custos-operacionais-section";
import { PaymentMethodsSection } from "@/features/payment-methods";
import { PwaSection } from "./sections/pwa-section";
import { SkuCleanupSection } from "./sections/sku-cleanup-section";
import { PrintSettingsSection } from "@/features/printing";


export const SETTINGS_SECTIONS: SettingsSectionDefinition[] = [
  {
    id: "empresa",
    title: "Empresa",
    description: "Dados cadastrais, regionalização e identidade.",
    hint: "Nome, CNPJ, endereço e informações que aparecem em cupons e documentos.",
    whenToUse: "Ao cadastrar sua empresa ou atualizar dados fiscais.",
    icon: Building2,
    group: "Conta",
    component: EmpresaSection,
    searchTerms: ["cnpj", "razao social", "endereco", "logo", "identidade", "empresa"],
  },
  {
    id: "cupom",
    title: "Cupom Não Fiscal",
    description: "Personalize o que aparece no cupom impresso após cada venda.",
    hint: "Logo, endereço, WhatsApp, vendedor, QR Code e mensagem final.",
    whenToUse: "Ao ajustar como o cupom é impresso ou compartilhado.",
    icon: Receipt,
    group: "Conta",
    component: CupomSection,
    searchTerms: ["cupom", "recibo", "impressao", "receipt", "vendedor", "qr", "whatsapp", "rodape"],
  },
  {
    id: "impressao",
    title: "Impressão",
    description: "Impressora padrão, largura do papel, margens e cópias.",
    hint: "Cupom térmico 58/80 mm, etiquetas e impressão automática após a venda.",
    whenToUse: "Ao configurar a impressora do balcão ou o layout de etiquetas.",
    icon: Printer,
    group: "Conta",
    component: PrintSettingsSection,
    searchTerms: [
      "impressao",
      "impressora",
      "termica",
      "etiqueta",
      "danfe",
      "escpos",
      "58mm",
      "80mm",
      "copias",
      "margem",
    ],
  },
  {
    id: "custos-operacionais",
    title: "Custos Operacionais",
    description: "Frete, embalagem, seguro e outros custos aplicados a novos produtos.",
    hint: "O sistema pré-preenche esses valores em cada novo cadastro. Cada produto pode ser ajustado individualmente.",
    whenToUse: "Ao padronizar custos que se repetem no cadastro de produtos.",
    icon: Package,
    group: "Conta",
    component: CustosOperacionaisSection,
    searchTerms: [
      "custo",
      "custos",
      "frete",
      "embalagem",
      "seguro",
      "operacional",
      "padrao",
      "default",
      "produto",
    ],
  },
  {
    id: "meios-pagamento",
    title: "Meios de Pagamento",
    description: "Taxas de recebimento por PIX, dinheiro, débito e crédito.",
    hint: "Toda venda calcula automaticamente o valor líquido usando esses valores. Bella IA, Painel Executivo e Relatórios usam o líquido para lucro e margem.",
    whenToUse: "Ao atualizar taxas cobradas pela adquirente ou pela conta PIX.",
    icon: Wallet,
    group: "Canais",
    component: PaymentMethodsSection,
    searchTerms: [
      "taxa",
      "taxas",
      "pix",
      "cartao",
      "credito",
      "debito",
      "dinheiro",
      "adquirente",
      "recebimento",
      "liquido",
      "parcelas",
      "meios de pagamento",
    ],
  },
  {
    id: "usuarios",
    title: "Usuários e Permissões",
    description: "Convide sua equipe e defina o que cada pessoa pode fazer.",
    hint: "Perfis (dono, gerente, operador) e permissões por módulo.",
    whenToUse: "Ao adicionar um novo colaborador ou revisar acessos.",
    icon: Users,
    group: "Conta",
    component: UsuariosSection,
    searchTerms: ["usuario", "usuarios", "permissao", "permissoes", "rbac", "equipe", "papel", "role"],
  },
  {
    id: "integracoes",
    title: "Integrações",
    description: "Conecte o NexOS a outros sistemas e serviços.",
    hint: "API pública, webhooks e integrações externas.",
    whenToUse: "Ao integrar com ERPs, marketplaces ou automações próprias.",
    icon: Plug,
    group: "Canais",
    component: IntegracoesSection,
    searchTerms: ["api", "webhook", "integracao", "chave", "token", "externo"],
  },
  {
    id: "bella-pay",
    title: "Bella Pay",
    description: "Receba por PIX, cartão e boleto direto do NexOS.",
    hint: "Meios de pagamento, taxas, parcelamento e conta de recebimento.",
    whenToUse: "Ao ativar cobranças ou ajustar taxas absorvidas.",
    icon: CreditCard,
    group: "Canais",
    component: BellaPaySection,
    searchTerms: ["pix", "cartao", "credito", "boleto", "cobranca", "asaas", "pagamento", "parcelamento", "taxa"],
  },
  {
    id: "discount-policy",
    title: "Política de Descontos",
    description: "Defina onde e quanto de desconto o operador pode conceder.",
    hint: "O sistema decide automaticamente. O operador não precisa lembrar da regra.",
    whenToUse: "Ao definir limites de desconto e formas de pagamento aceitas.",
    icon: Percent,
    group: "Canais",
    component: DiscountPolicySection,
    searchTerms: [
      "desconto",
      "descontos",
      "vendas",
      "politica",
      "pdv",
      "gerente",
      "limite",
      "pix",
      "dinheiro",
    ],
  },
  {

    id: "whatsapp",
    title: "WhatsApp",
    description: "Envie cobranças, comprovantes e campanhas.",
    hint: "Sessão conectada, templates e notificações automáticas.",
    whenToUse: "Para automatizar comunicação com clientes.",
    icon: MessageCircle,
    group: "Canais",
    component: WhatsappSection,
    searchTerms: ["whatsapp", "zap", "mensagem", "campanha", "template"],
  },
  {
    id: "preferencias",
    title: "Preferências",
    description: "Ajuste como o NexOS trabalha para você.",
    hint: "Vendas, PDV, financeiro, documentos e aparência em um só lugar.",
    whenToUse: "Ao personalizar o comportamento padrão do sistema.",
    icon: SlidersHorizontal,
    group: "Sistema",
    component: PreferenciasSection,
    searchTerms: [
      "preferencia",
      "vendas",
      "pdv",
      "cupom",
      "impressora",
      "tema",
      "escuro",
      "claro",
      "financeiro",
      "categoria",
      "conta",
      "documento",
      "pdf",
      "aparencia",
      "cor",
      "idioma",
    ],
  },
  {
    id: "backup",
    title: "Backup",
    description: "Seus dados estão seguros — cópia diária automática.",
    hint: "Frequência, retenção e exportação de dados.",
    whenToUse: "Para conferir segurança dos dados ou exportar histórico.",
    icon: DatabaseBackup,
    group: "Sistema",
    component: BackupSection,
    searchTerms: ["backup", "seguranca", "restaurar", "export", "exportacao", "dados"],
  },
  {
    id: "diagnostico",
    title: "Diagnóstico do Sistema",
    description: "Execute um Health Check completo do NexOS.",
    hint: "Testa conexões, integrações e configurações essenciais sem executar ações externas.",
    whenToUse: "Ao investigar falhas ou validar o ambiente após mudanças.",
    icon: Activity,
    group: "Sistema",
    component: DiagnosticoSection,
    searchTerms: ["diagnostico", "health", "check", "status", "monitoramento", "teste", "conexao"],
  },
  {
    id: "sku-cleanup",
    title: "Padronizar SKUs legados",
    description: "Renomeia produtos com SKU antigo (PROD-XXXXXX) para o padrão oficial.",
    hint: "Usa a mesma função que o recebimento de compras (CAT-MOD-COR-SEQ). Só altera o campo SKU do produto — vendas, estoque e histórico permanecem intactos. Toda renomeação é registrada em auditoria.",
    whenToUse: "Depois de importar compras antigas ou herdar produtos com SKU genérico.",
    icon: Wand2,
    group: "Sistema",
    component: SkuCleanupSection,
    searchTerms: ["sku", "padronizar", "legado", "renomear", "prod-", "cat-mod-cor", "codigo"],
    badge: { label: "Admin", tone: "new" },
  },
  {
    id: "pwa",
    title: "Aplicativo Instalado (PWA)",
    description: "Diagnóstico e limpeza do NexOS instalado no dispositivo.",
    hint: "Lista Service Workers e caches ativos, e permite limpar quando o app insistir em abrir uma versão antiga.",
    whenToUse: "Se o app instalado não estiver recebendo atualizações após um novo deploy.",
    icon: Smartphone,
    group: "Sistema",
    component: PwaSection,
    searchTerms: [
      "pwa",
      "aplicativo",
      "instalado",
      "service worker",
      "sw",
      "cache",
      "atualizar",
      "atualizacao",
      "versao",
      "antigo",
      "travado",
      "limpar",
    ],
  },
];
