/**
 * Central catalog of application route paths.
 */
export const ROUTES = {
  home: "/",
  auth: "/auth",
  resetPassword: "/reset-password",
  onboarding: "/onboarding",
  dashboard: "/dashboard",
  products: "/produtos",
  categories: "/categorias",
  inventory: "/estoque",
  inventoryReconciliation: "/estoque/reconciliacao",
  purchases: "/compras",
  suppliers: "/fornecedores",
  imports: "/importacoes",
  customers: "/clientes",
  sales: "/vendas",
  pdv: "/pdv",
  cash: "/caixa",
  finance: "/financeiro",
  fiscalHealth: "/financeiro/saude-fiscal",
  fiscal: "/fiscal",
  fiscalDocuments: "/fiscal/notas",
  fiscalConfig: "/fiscal/configuracao",
  bellaPay: "/bella-pay",
  agenda: "/agenda",
  marketing: "/marketing",
  campaigns: "/campanhas",
  crm: "/crm",
  reports: "/relatorios",
  executivePanel: "/painel-executivo",
  indicators: "/indicadores",

  bella: "/bella",
  bellaAccountant: "/bella-contadora",
  bellaKnowledge: "/bella-conhecimento",
  settings: "/configuracoes",
  processes: "/processamentos",
  documents: "/documentos",
  platformHealth: "/saude-plataforma",
  whatsapp: "/whatsapp",
  commercialDashboard: "/inteligencia-comercial/dashboard",
  commercialPolicy: "/inteligencia-comercial/politica-empresa",
  commercialCategories: "/inteligencia-comercial/categorias",
  commercialSimulator: "/inteligencia-comercial/simulador",
  commercialReview: "/inteligencia-comercial/revisao-precos",
  commercialRecalculate: "/inteligencia-comercial/recalcular-precos",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
