/**
 * Bella IA — API pública do módulo `ai/` (Fase 1).
 *
 * NÃO exporta: providers, executores internos, DTOs de infra.
 * Consumidores (server functions / UI wrappers) só devem tocar aqui.
 */
export * from "./contracts";
export { defaultIntentRouter, createIntentRouter } from "./intents";
export { defaultPromptRegistry, createPromptRegistry } from "./prompts";
export {
  createCommercialTools,
  createToolRegistry,
  createDefaultToolExecutors,
  type ToolExecutors,
} from "./tools";
export {
  createOrchestrator,
  systemOrchestratorClock,
  type OrchestratorDeps,
  type HandleInput,
  type HandleOutput,
} from "./orchestrator";
export { applyOutputGuardrails } from "./guardrails";
export {
  SAFE_ACTIONS,
  ACTION_PROPOSAL_VERSION,
  ACTION_RESULT_VERSION,
  actionProposalSchema,
  actionExecutionResultSchema,
  createActionRegistry,
  createActionExecutor,
  guardActionRequest,
  guardActionConfirmation,
  type SafeActionId,
  type ActionProposal,
  type ActionExecutionResult,
  type ActionImpact,
  type ActionRisk,
  type ActionRegistry,
  type ActionDefinition,
  type ActionSessionCtx,
  type ProposeInput,
  type ConfirmInput,
  type ProposeOutput,
  type ExecuteOutput,
} from "./actions";
export {
  formatActionProposal,
  formatActionResult,
} from "./formatter";
export {
  WORKFLOWS,
  WORKFLOW_PROPOSAL_VERSION,
  WORKFLOW_REPORT_VERSION,
  workflowProposalSchema,
  workflowReportSchema,
  createWorkflowRegistry,
  createWorkflowExecutor,
  guardWorkflowRequest,
  guardWorkflowConfirmation,
  guardWorkflowTenant,
  type WorkflowId,
  type WorkflowProposal,
  type WorkflowReport,
  type WorkflowItemResult,
  type WorkflowImpact,
  type WorkflowRisk,
  type WorkflowTarget,
  type WorkflowRegistry,
  type WorkflowDefinition,
  type WorkflowSessionCtx,
  type WorkflowProposeInput,
  type WorkflowConfirmInput,
  type WorkflowProposeOutput,
  type WorkflowConfirmOutput,
} from "./workflows";
export {
  SESSION_CONTEXT_VERSION,
  REFERENCE_TYPES,
  DEFAULT_EXPIRATION,
  sessionContextSchema,
  sessionRefSchema,
  sessionActionRefSchema,
  createSessionMemory,
  systemSessionClock,
  createContextResolver,
  resolveReference,
  guardTenant,
  guardActionReuse,
  guardWorkflowReuse,
  isExpired,
  contextAgeMs,
  contextIdleMs,
  type ReferenceType,
  type SessionContext,
  type SessionContextPatch,
  type SessionRef,
  type SessionActionRef,
  type SessionResolutionAudit,
  type SessionScope,
  type SessionMemory,
  type SessionMemoryClock,
  type ExpirationPolicy,
  type ContextResolver,
  type ContextResolveInput,
  type ContextResolveOutput,
  type SessionGuardResult,
  type SessionGuardCode,
} from "./session";
export {
  BRIEFING_VERSION,
  BRIEFING_SECTIONS,
  BRIEFING_SOURCES,
  BRIEFING_SOURCE_REGISTRY,
  BRIEFING_SUGGESTED_QUESTIONS,
  briefingCardSchema,
  dailyBriefingSchema,
  systemBriefingClock,
  createBriefingBuilder,
  formatDailyBriefing,
  type BriefingCard,
  type BriefingClock,
  type BriefingConfidence,
  type BriefingSection,
  type BriefingSourceDescriptor,
  type BriefingSourceId,
  type BriefingTone,
  type DailyBriefing,
  type BriefingBuilder,
  type BriefingBuilderDeps,
  type BuildBriefingInput,
} from "./briefing";
